name: flutter_speech_to_text_tutorial
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  speech_to_text: ^6.3.0
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.2.1
  firebase_core: 2.25.4
  firebase_auth: ^4.4.0
  flutter_blue: 0.8.0
  cloud_firestore: ^4.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/google_logo.png
    - lib/assets/ecoute_logo.png
    - lib/assets/audi_en_texte.png
    - lib/assets/interrogation.png
