// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC21iSZbS3niVNLfUW_OOuON-bqEsJl2Ac',
    appId: '1:420896563080:web:4a66b2e010794c92dda43d',
    messagingSenderId: '420896563080',
    projectId: 'hearme-210',
    authDomain: 'hearme-210.firebaseapp.com',
    storageBucket: 'hearme-210.appspot.com',
    measurementId: 'G-M4QJTTMX6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi0idR1SHYybu8lHNkFFzsvnztk1sUho0',
    appId: '1:420896563080:android:e48ad3d2a2628e70dda43d',
    messagingSenderId: '420896563080',
    projectId: 'hearme-210',
    storageBucket: 'hearme-210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDApbxwDZ2JdG168ICEt-IrnLnNKuWcHWc',
    appId: '1:420896563080:ios:37bea8f50d4b6d3edda43d',
    messagingSenderId: '420896563080',
    projectId: 'hearme-210',
    storageBucket: 'hearme-210.appspot.com',
    iosClientId: '420896563080-73sukasvg1fd4knrags5240geq78ja21.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSpeechToTextTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDApbxwDZ2JdG168ICEt-IrnLnNKuWcHWc',
    appId: '1:420896563080:ios:ff1a14fa075b63d4dda43d',
    messagingSenderId: '420896563080',
    projectId: 'hearme-210',
    storageBucket: 'hearme-210.appspot.com',
    iosClientId: '420896563080-k5ttsqshm0k4gfju5h8hflmquh3ovrhd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSpeechToTextTutorial.RunnerTests',
  );
}
